server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://jason.kai-7001.cn:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    myUser.serviceId: employee-plat-provider #这是调用满足条件的服务名，注意要小写
    myUser.path: /user/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services"  #这是所有路径的前缀
  #访问地址如下：http://localhost:9527/services/user/provider/user/3