server:
  port: 7001
spring:
  application:
    name: YADAO-EUREKA
eureka:
  instance:
    hostname: jason.kai-7001.cn
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置
